const mongoose=require("mongoose");

const userSchema=new mongoose.Schema({
    username:{
        type:String,
        required:true,
        min:3,
        max:20,
        unique:true
       },
       email:{
        type:String,
        required:true,
        max:50,
        unique:true
       },
       password:{
           type:String,
           required:true,
           min:6
       },
       profilePicture:{
           type:String,
           default:""
       },
       coverPicture:{
        type:String,
        default:""
       },
       followers:{
           type:Array,
           dafault:[]
       },
       following:{
        type:Array,
        dafault:[]
       },
       isAdmin:{
        type:Boolean,
        default:false
        },
        description:{
            type:String,
            max:50
        },
        city:{
            type:String,
            max:50
        },
        from:{
            type:String,
            max:50
        },
        relationship:{
            type:String,
            enum:["single","relationship","complicated"],
        }

},{timestamps:true});
module.exports=mongoose.model("User",userSchema);